// Samson Portfolio jQuery
$(document).ready(function(){}


{$("#title").draggable({containment:"document"});$("#wp7").draggable({containment:"document",handle:"#frame .top, .left, .right, .bottom"});$(".lock-screen").draggable({axis:"y",stop:function(){$(this).animate({top:"-437px"},500,function(){$(".lock-screen").addClass("hidden");
$(".step-1").fadeOut(function(){$(".step-2").fadeIn(function(){setTimeout(function(){$(".step-2").fadeOut(function(){$(".step-3").fadeIn()})},3E3)})})})}});$(".boxes").sortable({distance:3,helper:'clone'});$(".box-small6").sortable({distance:3,helper:'clone'});$(".lists").sortable({distance:3,helper:'clone'});$(".search").click(function(){$(".lock-screen").hasClass("hidden")&&$("#search").hasClass("hidden")&&($("#search").append('<iframe width="690" height="550" scrolling="auto" frameborder="0" src="http://www.bing.com/samsontoor";></iframe>'),
$(".window-size").not("#search").animate({left:"-488px"},500,function(){$(this).addClass("hidden");$(this).css({left:"-50px"})}),$("#search").removeClass("hidden"),$(".home-screen").animate({left:"-288px"},500))});$(".phone").click(function(){$("#phone").removeClass("hidden");$(".home-screen").animate({left:"-288px"},500)});$("#phone .keys .key").click(function(){var c=$(this).attr("class").split("key ").pop(),d=$("#phone .number").text().length;d<14&&(d==0&&$("#phone .number").append("("),d==4&&$("#phone .number").append(") "),
d==9&&$("#phone .number").append("-"),c!=="star"&&c!=="pound"&&($("#phone .number").append(c),$("#phone .numberclean").append(c)))});$("#phone .backspace").click(function(){$("#phone .number").empty();$("#phone .numberclean").empty()});$("#phone .dial-pad .call").click(function(){var c=$("#phone .numberclean").text().length,d=$("#phone .numberclean").text();c==10&&(e("f90fedd2c25082f0e19e3430740a82fbf9e3c668",d,"Anonymous"),$("#phone .incoming").animate({top:"0px"},500,function(){$("#phone .dial-pad").fadeTo(500,
0.5);setTimeout(function(){$("#phone .incoming").animate({top:"-157px"},500);$("#phone .dial-pad").fadeTo(500,1)},3E4);$("#phone .number").empty();$("#phone .numberclean").empty()}))});$(".email").click(function(){$("#email").append('<iframe width="288" height="437" scrolling="no" frameborder="0" src="email.php"></iframe>');$("#email").removeClass("hidden");$(".home-screen").animate({left:"-288px"},500)});$(".social").click(function(){$("#social").removeClass("hidden");$(".home-screen").animate({left:"-288px"},
500)});$(".buzz").click(function(){$("#buzz").removeClass("hidden");$(".home-screen").animate({left:"-288px"},500)});var g=1;$(".resume").click(function(){$("#resume").removeClass("hidden");$(".home-screen").animate({left:"-288px"},500);g==1&&($("#floaty-thing .resumehelper").fadeIn(),g++)});$("#resume .tab").click(function(){$("#resume .tab").removeClass("selected");
$(this).addClass("selected");switch($(this).attr("class").split(" ")[1]){case "experience":$("#resume .title").animate({left:"15px"},500);$("#resume .tabs").animate({left:"15px"},500);$("#resume .pages").animate({left:"0px"},500);$("#resume").animate({"background-position":"0px"},500);break;case "education":$("#resume .title").animate({left:"-20px"},500);$("#resume .tabs").animate({left:"-105px"},500);$("#resume .pages").animate({left:"-288px"},500);$("#resume").animate({"background-position":"-288px"},
500);g==2&&$("#floaty-thing .resumehelper").fadeOut();break;case "events":$("#resume .title").animate({left:"-55px"},500);$("#resume .tabs").animate({left:"-235px"},500);$("#resume .pages").animate({left:"-530px"},500);$("#resume").animate({"background-position":"-530px"},500);break;case "skills":$("#resume .title").animate({left:"-90px"},500);$("#resume .tabs").animate({left:"-370px"},500);$("#resume .pages").animate({left:"-795px"},500);$("#resume").animate({"background-position":"-795px"},500);
break;case "code":$("#resume .title").animate({left:"-125px"},500),$("#resume .tabs").animate({left:"-440px"},500),$("#resume .pages").animate({left:"-1060px"},500),$("#resume").animate({"background-position":"-1060px"},500)}});$(".map").click(function(){$("#map").append('<iframe Name="mapFrame" scrolling="no" width="288" height="437" frameborder="0" src="http://www.bing.com/maps/embed/?lvl=11&amp;cp=47.642521~-122.130608&amp;sty=r&amp;draggable=true&amp;v=2&amp;dir=0&amp;where1=Redmond%2C+WA&amp;form=LMLTEW&amp;pp=47.642521~-122.130608&amp;emid=dc82f11-bfd2-ac21-1839-7d896b05420b&amp;w=288&amp;h=437"></iframe>');
$("#map").removeClass("hidden");$(".home-screen").animate({left:"-288px"},500)});$(".gallery").click(function(){$("#gallery").append('<iframe width="288" height="437" scrolling="no" frameborder="0" src="flickr.html"></iframe>');$("#gallery").removeClass("hidden");$(".home-screen").animate({left:"-288px"},500)});$(".settings").click(function(){$("#settings").removeClass("hidden");$(".home-screen").animate({left:"-288px"},500)});$(".home, .back").click(function(){$(".lock-screen").hasClass("hidden")&&
($(".home-screen").animate({left:"0px"},500,function(){$(".window-size").addClass("hidden");$("#search, #map, #gallery, #email").empty()}),$(".home-screen").css("left")!="-288px"&&$(".boxes").css("left")=="-204px"&&f());g==2&&$("#floaty-thing .resumehelper").fadeOut()});$(".arrow").click(function(){f()});$("#settings .colors li").click(function(){var c=$(this).attr("class").split("color ").pop();$change=$("#content .home-screen .box, #content .home-screen li.list div");$("#settings .colors li").css({"font-size":"20px",
"font-weight":"normal"});$(this).css({"font-size":"22px","font-weight":"bold"});switch(c){case "blue":$change.css({"background-color":"#1BA1E2"});break;case "green":$change.css({"background-color":"#339933"});break;case "orange":$change.css({"background-color":"#F09609"});break;case "purple":$change.css({"background-color":"#A200FF"});break;case "red":$change.css({"background-color":"#E51400"})}});$("#sharebutton").click(function(){$("#share").removeClass("hidden");$(this).addClass("hidden");$("#share").draggable({containment:"document",
handle:"#share"});$("#share .item").eq(0).append('<fb:like send="false" layout="box_count" width="55" show_faces="false"></fb:like>');$("#share .item").eq(1).append('<iframe scrolling="no" frameborder="0" allowtransparency="true" width="51" height="63" src="http://www.stumbleupon.com/badge/embed/5/?url=http://uxdefender.com"></iframe>');$("#share .item").eq(2).append('<a href="http://twitter.com/share" data-via="uxsamson" data-related="samson" data-count="vertical" class="twitter-share-button">Tweet</a>');
//$.getScript("https://apis.google.com/js/plusone.js");$("#share .item").eq(3).append('<g:plusone size="tall"></g:plusone>');$("#share .item").eq(4).append('<iframe width="51" scrolling="no" height="69" frameborder="0" src="http://www.reddit.com/static/button/button2.html?width=51&amp;url=http://.com"></iframe>');h();i();
$.getScript("http://platform.twitter.com/widgets.js")});goldenEgg()});function goldenEgg(){return $(this).each(function(){var e=[];$(this).keydown(function(f){e.push(f.keyCode);if(e.toString().indexOf("38,38,40,40,37,39,37,39,66,65")>=0)$(this).unbind("keydown"),window.location="http://www.linkedin.com/in/samsontoor"},!0)})};